--liquibase formatted sql
--dlevazhinsky:1
CREATE TABLE Person
(
    user_id  INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(100) UNIQUE NOT NULL
);

--dlevazhinsky:2
CREATE TABLE Courier
(
    id   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(10)
);

--dlevazhinsky:3
CREATE TABLE Person_Profile
(
    id           INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      INT UNIQUE REFERENCES Person (user_id) ON DELETE CASCADE,
    courier_Id   INT UNIQUE REFERENCES Courier (id) ON DELETE CASCADE,
    name         VARCHAR(100) UNIQUE NOT NULL,
    updated_date TIMESTAMP,
    role         VARCHAR(10),
    status       INT     default 0,
    is_active     BOOLEAN default true
);

--dlevazhinsky:4
CREATE table Food_Order
(
    id         int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    INT REFERENCES Person_Profile (USER_ID) ON DELETE CASCADE,
    courier_id INT REFERENCES Courier (id) ON DELETE CASCADE,
    status VARCHAR(20)
);

--dlevazhinsky:5
CREATE TABLE PersonHistory
(
    id      INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT REFERENCES Person_Profile (user_id) ON DELETE CASCADE,
    date    TIMESTAMP,
    status  VARCHAR(10)
);

--dlevazhinsky:6
CREATE TABLE Restaurant
(
    id              INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(50),
    is_active        boolean DEFAULT TRUE,
    rating          FLOAT   DEFAULT 5.0 CHECK (rating BETWEEN 0.0 AND 5.0),
    restaurant_type VARCHAR(10)
);


--dlevazhinsky:7
CREATE TABLE Food_Menu
(
    id            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    restaurant_id INT REFERENCES Restaurant (id)
);


--dlevazhinskyL:8
CREATE TABLE Food_Cart
(
    id                INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    person_profile_id INT references Person_Profile (id),
    restaurant_id     INT references Restaurant (ID)
);


--dlevazhinsky:9
CREATE TABLE Food_Dish
(
    id           INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dish_name    VARCHAR(50),
    price        INT default 0,
    menu_id      INT REFERENCES Food_Menu (id),
    is_available Boolean default true,
    food_cart_id  INT references Food_Cart (id),
    food_order_id INT references Food_Order(id),
    quantity int default 1
);


--dlevazhinsky:10
CREATE TABLE Review
(
    id            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rating        FLOAT DEFAULT 0.0,
    comment       VARCHAR(100),
    restaurant_id INT REFERENCES Restaurant (id),
    person_id     INT REFERENCES Person_Profile (id)
);



